volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: pismokb/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    env_file: .env
    image: pismokb/taski_frontend
    volumes:
      - static:/frontend_static

  gateway:
    image: pismokb/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80